<h2 style="text-align: center;">🔹 FSDS Task 10 – NumPy Crash Course & Built-in Functions</h2>

### 👨‍💻 Prepared by: Mubasshir Ahmed  
### 🕘 FSDS @10AM | Guided by: Senapati sir

---

### 📘 What This Notebook Covers:

This notebook is a comprehensive walkthrough of **NumPy**, a core library for numerical computing in Python.  
We’ll follow two official task PDFs and explore NumPy from **basic to advanced level**, including built-in functions and real-time examples.

---

### 📗 Topics Covered:

1. 📌 Introduction to NumPy  
2. 📌 Creating NumPy Arrays  
3. 📌 Array Dimensions & Shapes  
4. 📌 Array Indexing & Slicing  
5. 📌 Array Operations (Arithmetic & Logical)  
6. 📌 Universal Functions (ufuncs)  
7. 📌 Built-in NumPy Functions  
8. 📌 Random Module & Seeding  
9. 📌 Aggregate Functions: min, max, sum, mean, etc.  
10. 📌 Advanced Topics: reshape, flatten, stack, split, etc.  
11. 📌 Broadcasting  
12. 📌 Practical Examples & Summary

---

> ✅ Each section includes clean code blocks, inline output comments, and personalized examples.


<h2 style="text-align: center;">🔹 Section 1 – Introduction to NumPy</h2>

NumPy (Numerical Python) is the foundational package for numerical computing in Python.  
It provides support for:
- Multidimensional arrays and matrices
- Mathematical functions for array operations
- Efficient broadcasting and vectorization

We first import the library and check its version.


In [25]:
# Importing NumPy library
import numpy as np

# Checking the version of NumPy
print("NumPy Version:", np.__version__)  # ➤ NumPy Version: e.g., 1.26.4


NumPy Version: 1.26.4


In [26]:
# Traditional Python List
import time

python_list = list(range(1, 1000001))
start = time.time()
python_result = [x * 2 for x in python_list]
end = time.time()
print("Time taken using Python list:", end - start, "seconds")  # ➤ Slower

# NumPy Array
numpy_array = np.array(python_list)
start = time.time()
numpy_result = numpy_array * 2
end = time.time()
print("Time taken using NumPy array:", end - start, "seconds")  # ➤ Faster


Time taken using Python list: 0.21401262283325195 seconds
Time taken using NumPy array: 0.0020008087158203125 seconds


<h2 style="text-align: center;">🔹 Section 2 – Creating NumPy Arrays</h2>

NumPy arrays can be created using the `np.array()` function or other specialized functions like `arange()`, `zeros()`, `ones()`, `linspace()`, etc.

We’ll explore:
- Creating 1D, 2D, and 3D arrays
- Specifying data types
- Using array-creation shortcuts


In [27]:
# Creating a 1D array
arr_1d = np.array([10, 20, 30, 40])
print("1D Array:", arr_1d)  # ➤ [10 20 30 40]

# Creating a 2D array
arr_2d = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr_2d)  
# ➤ [[1 2]
#     [3 4]]

# Creating a 3D array
arr_3d = np.array(
    [
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
    ]
    )
print("3D Array:\n", arr_3d)  
# ➤ [[[1 2]
#      [3 4]]
#     [[5 6]
#      [7 8]]]


1D Array: [10 20 30 40]
2D Array:
 [[1 2]
 [3 4]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Creating array with float data type
float_array = np.array([1, 2, 3], dtype=float)
print("Float Array:", float_array)  # ➤ [1. 2. 3.]


Float Array: [1. 2. 3.]


In [29]:
print("Array of zeros:", np.zeros(5))  # ➤ [0. 0. 0. 0. 0.]

print("Array of ones:", np.ones((2, 3)))  
# ➤ [[1. 1. 1.]
#     [1. 1. 1.]]

print("Empty array (uninitialized):", np.empty(4))  
# ➤ [random small numbers]

print("Range array:", np.arange(0, 10, 2))  # ➤ [0 2 4 6 8]

print("Linspace array:", np.linspace(0, 1, 5))  # ➤ [0.   0.25 0.5  0.75 1.  ]


Array of zeros: [0. 0. 0. 0. 0.]
Array of ones: [[1. 1. 1.]
 [1. 1. 1.]]
Empty array (uninitialized): [4.24399158e-314 8.48798317e-314 1.27319747e-313 1.69759663e-313]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


<h2 style="text-align: center;">🔹 Section 3 – Array Dimensions & Shapes</h2>

Understanding the shape and dimensionality of NumPy arrays is key to working with them efficiently.  
In this section, we’ll explore:
- `ndim` → number of dimensions
- `shape` → number of elements in each dimension
- `size` → total number of elements
- `reshape()` → changing the structure of arrays


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Dimensions (ndim):", arr.ndim)     # ➤ 2
print("Shape:", arr.shape)                # ➤ (2, 3)
print("Size:", arr.size)                  # ➤ 6
print("Data type:", arr.dtype)            # ➤ int64 or int32 depending on system


Array:
 [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Data type: int32


In [31]:
# Reshaping a 1D array to 2D
arr_1d = np.arange(12)
print("Original 1D array:", arr_1d)

arr_reshaped = arr_1d.reshape((3, 4))
print("Reshaped to 3x4:\n", arr_reshaped)


Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
reshaped = np.arange(15).reshape(5, 3)
print("Reshaped 5x3 Array:\n", reshaped)


Reshaped 5x3 Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


<h2 style="text-align: center;">🔹 Section 4 – Array Indexing & Slicing</h2>

Just like Python lists, NumPy arrays support:
- **Indexing**: Accessing individual elements
- **Slicing**: Accessing ranges/sub-arrays
- Works on 1D, 2D, and higher-dimensional arrays

We’ll now explore both techniques.


In [33]:
#Indexing in 1D Arrays
arr = np.array([10, 20, 30, 40, 50])

print("Element at index 0:", arr[0])     # ➤ 10
print("Element at index 3:", arr[3])     # ➤ 40
print("Last element (negative index):", arr[-1])  # ➤ 50


Element at index 0: 10
Element at index 3: 40
Last element (negative index): 50


In [34]:
#Indexing in 2D Arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Element at row 0, col 2:", arr_2d[0, 2])  # ➤ 3
print("Element at row 1, col 0:", arr_2d[1, 0])  # ➤ 4


Element at row 0, col 2: 3
Element at row 1, col 0: 4


In [35]:
#  Slicing in 1D Arrays
arr = np.array([10, 20, 30, 40, 50, 60])

print("Elements from index 1 to 4:", arr[1:5])      # ➤ [20 30 40 50]
print("Every 2nd element:", arr[::2])              # ➤ [10 30 50]
print("Reverse array:", arr[::-1])                 # ➤ [60 50 40 30 20 10]


Elements from index 1 to 4: [20 30 40 50]
Every 2nd element: [10 30 50]
Reverse array: [60 50 40 30 20 10]


In [36]:
# Slicing a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("First 2 rows:\n", arr_2d[:2])               
# ➤ [[1 2 3]
#     [4 5 6]]

print("First 2 columns:\n", arr_2d[:, :2])         
# ➤ [[1 2]
#     [4 5]
#     [7 8]]

print("Bottom-right 2x2 block:\n", arr_2d[1:, 1:])  
# ➤ [[5 6]
#     [8 9]]


First 2 rows:
 [[1 2 3]
 [4 5 6]]
First 2 columns:
 [[1 2]
 [4 5]
 [7 8]]
Bottom-right 2x2 block:
 [[5 6]
 [8 9]]


<h2 style="text-align: center;">🔹 Section 5 – Array Arithmetic & Logical Operations</h2>

NumPy allows element-wise operations on arrays, just like mathematical expressions.  
These operations are **vectorized**, making them faster than Python loops.

We’ll cover:
- Arithmetic operations (`+`, `-`, `*`, `/`, `**`)
- Comparison operations (`==`, `!=`, `>`, `<`, etc.)
- Logical operations (`&`, `|`, `~`)


In [38]:
#  Arithmetic Operation 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", arr1 + arr2)         # ➤ [5 7 9]
print("Subtraction:", arr2 - arr1)      # ➤ [3 3 3]
print("Multiplication:", arr1 * arr2)   # ➤ [ 4 10 18]
print("Division:", arr2 / arr1)         # ➤ [4. 2.5 2.]
print("Exponentiation:", arr1 ** 2)     # ➤ [1 4 9]


Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Exponentiation: [1 4 9]


In [39]:
# Comparison Operations
print("Equal:", arr1 == arr2)       # ➤ [False False False]
print("Not Equal:", arr1 != arr2)   # ➤ [ True  True  True]
print("Greater:", arr2 > arr1)      # ➤ [ True  True  True]


Equal: [False False False]
Not Equal: [ True  True  True]
Greater: [ True  True  True]


In [41]:
# Logical Operations
# Logical AND (element-wise)
print("Logical AND:", np.logical_and(arr1 > 0, arr2 > 4))  
# ➤ [False  True  True]

# Logical OR
print("Logical OR:", np.logical_or(arr1 > 2, arr2 > 5))    
# ➤ [False False  True]

# Logical NOT
print("Logical NOT arr1 > 2:", np.logical_not(arr1 > 2))   
# ➤ [ True  True False]


Logical AND: [False  True  True]
Logical OR: [False False  True]
Logical NOT arr1 > 2: [ True  True False]


<h2 style="text-align: center;">🔹 Section 6 – NumPy Built-in Functions</h2>

NumPy comes with many powerful built-in functions that simplify numeric computation.  
We’ll explore:
- Aggregation functions like `sum()`, `min()`, `max()`, `mean()`, `std()`
- Axis-specific operations
- Rounding, exponentials, and square roots


In [42]:
# aggregation functions like `sum()`, `min()`, `max()`, `mean()`, `std()`
# Aggregation functions are used to compute summary statistics over arrays.

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum of all elements:", np.sum(arr))           # ➤ 21
print("Minimum value:", np.min(arr))                 # ➤ 1
print("Maximum value:", np.max(arr))                 # ➤ 6
print("Mean value:", np.mean(arr))                   # ➤ 3.5
print("Standard deviation:", np.std(arr))            # ➤ 1.7078...


Sum of all elements: 21
Minimum value: 1
Maximum value: 6
Mean value: 3.5
Standard deviation: 1.707825127659933


In [43]:
print("Row-wise sum:", np.sum(arr, axis=1))          # ➤ [ 6 15]
print("Column-wise sum:", np.sum(arr, axis=0))       # ➤ [5 7 9]

Row-wise sum: [ 6 15]
Column-wise sum: [5 7 9]


In [44]:
arr = np.array([1.2, 2.5, 3.7])

print("Rounded values:", np.round(arr))              # ➤ [1. 2. 4.]
print("Square roots:", np.sqrt(arr))                 # ➤ [1.095 1.581 1.923]
print("Exponentials:", np.exp(arr))                  # ➤ [ 3.32 12.18 40.45]


Rounded values: [1. 2. 4.]
Square roots: [1.09544512 1.58113883 1.92353841]
Exponentials: [ 3.32011692 12.18249396 40.44730436]


<h2 style="text-align: center;">🔹 Section 7 – Array Copying & Views</h2>

In NumPy, assignment doesn’t create a new copy of an array — it creates a **view** (reference).  
To truly copy an array, use the `.copy()` method.

We'll explore:
- Difference between views and copies
- How modifying one affects the other


In [45]:
original = np.array([10, 20, 30])
view = original  # No copy, just a reference

view[0] = 99
print("Original after modifying view:", original)   # ➤ [99 20 30]


Original after modifying view: [99 20 30]


In [46]:
original = np.array([10, 20, 30])
copy_array = original.copy()

copy_array[0] = 999
print("Original after modifying copy:", original)     # ➤ [10 20 30]
print("Modified copy:", copy_array)                   # ➤ [999  20  30]


Original after modifying copy: [10 20 30]
Modified copy: [999  20  30]


In [47]:
arr_2d = np.array([[1, 2], [3, 4]])
copy_2d = arr_2d.copy()

copy_2d[0, 0] = 99
print("Original 2D:\n", arr_2d)        # ➤ [[1 2], [3 4]]
print("Copied 2D:\n", copy_2d)         # ➤ [[99 2], [3 4]]


Original 2D:
 [[1 2]
 [3 4]]
Copied 2D:
 [[99  2]
 [ 3  4]]


<h2 style="text-align: center;">🔹 Section 8 – Reshape, Flatten & Transpose</h2>

NumPy arrays offer powerful ways to manipulate their structure without changing data:
- `reshape()` changes shape
- `flatten()` converts multi-D to 1D
- `transpose()` swaps axes (rows ↔ columns)


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # Convert 1D to 2x3 2D array

print("Original:", arr)           
# ➤ [1 2 3 4 5 6]

print("Reshaped:\n", reshaped)    
# ➤ [[1 2 3]
#     [4 5 6]]


Original: [1 2 3 4 5 6]
Reshaped:
 [[1 2 3]
 [4 5 6]]


In [49]:
arr_2d = np.array([[10, 20], [30, 40]])
flat = arr_2d.flatten()

print("Flattened array:", flat)      
# ➤ [10 20 30 40]


Flattened array: [10 20 30 40]


In [50]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
transposed = arr_2d.T

print("Original:\n", arr_2d)
# ➤ [[1 2 3]
#     [4 5 6]]

print("Transposed:\n", transposed)
# ➤ [[1 4]
#     [2 5]
#     [3 6]]


Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


<h2 style="text-align: center;">🔹 Section 9 – Stacking and Splitting Arrays</h2>

NumPy allows combining and breaking arrays using functions like:
- `hstack()` → horizontal stacking
- `vstack()` → vertical stacking
- `split()` / `hsplit()` / `vsplit()` → for breaking arrays


In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Horizontal stack (1D arrays become wider)
h = np.hstack((a, b))
print("Horizontal Stack:", h)          
# ➤ [1 2 3 4 5 6]

# Vertical stack (1D arrays become rows)
v = np.vstack((a, b))
print("Vertical Stack:\n", v)          
# ➤ [[1 2 3]
#     [4 5 6]]


Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [52]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Stack along a new third axis
print("Stacked along depth (axis=2):\n", np.dstack((x, y)))
# ➤ [[[1 5]
#      [2 6]]
#     [[3 7]
#      [4 8]]]


Stacked along depth (axis=2):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [53]:
arr = np.array([10, 20, 30, 40, 50, 60])
splitted = np.split(arr, 3)
print("Split into 3 parts:", splitted)   
# ➤ [array([10, 20]), array([30, 40]), array([50, 60])]


Split into 3 parts: [array([10, 20]), array([30, 40]), array([50, 60])]


<h2 style="text-align: center;">🔹 Section 10 – NumPy Random Module</h2>

NumPy provides a submodule called `numpy.random` to generate random numbers.  
We’ll cover:
- Generating random integers, floats
- Random sampling from arrays
- Seeding for reproducibility


In [54]:
# Random integers between 1 and 10 (excluding 10)
rand_ints = np.random.randint(1, 10, size=5)
print("Random Integers:", rand_ints)  
# ➤ e.g., [2 7 1 4 9]

# Random floats between 0 and 1
rand_floats = np.random.rand(3)
print("Random Floats:", rand_floats)  
# ➤ e.g., [0.12 0.64 0.78]


Random Integers: [4 5 5 1 2]
Random Floats: [0.88353909 0.53039152 0.5639873 ]


In [61]:
arr = np.array([100, 200, 300, 400, 500])
sample = np.random.choice(arr, size=3)
print("Random sample:", sample)        
# ➤ e.g., [200 500 100]


Random sample: [500 400 200]


In [85]:
np.random.seed(42)
print("Same output every time:", np.random.rand(3))  
# ➤ [0.3745 0.9507 0.7319] – fixed due to seed


Same output every time: [0.37454012 0.95071431 0.73199394]


<h2 style="text-align: center;">🔹 Section 11 – NumPy Math & Utility Functions</h2>

NumPy provides many built-in math and utility functions, including:
- `np.sqrt()`, `np.exp()`, `np.log()`, `np.sin()`, `np.cos()`
- `np.unique()`, `np.sort()`, `np.where()`, `np.count_nonzero()`


In [87]:
# Math Functions
arr = np.array([1, 4, 9, 16])

print("Square roots:", np.sqrt(arr))          # ➤ [1. 2. 3. 4.]
print("Exponential:", np.exp(arr))            # ➤ e.g., [2.7 54.6 ...]
print("Natural log:", np.log(arr))            # ➤ [0. 1.38 2.19 2.77]


Square roots: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Natural log: [0.         1.38629436 2.19722458 2.77258872]


In [86]:
# Trigonometric Functions
angles = np.array([0, np.pi/2, np.pi])
print("sin:", np.sin(angles))                 # ➤ [0. 1. 0.]
print("cos:", np.cos(angles))                 # ➤ [1. 0. -1.]


sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [88]:
# Utility Functions
arr = np.array([4, 2, 7, 2, 5, 7, 2])

print("Unique values:", np.unique(arr))       # ➤ [2 4 5 7]
print("Sorted array:", np.sort(arr))          # ➤ [2 2 2 4 5 7 7]
print("Index of 5s:", np.where(arr == 5))     # ➤ (array([4]),)
print("Count of non-zero elements:", np.count_nonzero(arr))  
# ➤ 7


Unique values: [2 4 5 7]
Sorted array: [2 2 2 4 5 7 7]
Index of 5s: (array([4], dtype=int64),)
Count of non-zero elements: 7


In [89]:
arr = np.array([4, 2, 7, 2, 5, 7, 2])

print("Unique values:", np.unique(arr))       # ➤ [2 4 5 7]
print("Sorted array:", np.sort(arr))          # ➤ [2 2 2 4 5 7 7]
print("Index of 5s:", np.where(arr == 5))     # ➤ (array([4]),)
print("Count of non-zero elements:", np.count_nonzero(arr))  
# ➤ 7


Unique values: [2 4 5 7]
Sorted array: [2 2 2 4 5 7 7]
Index of 5s: (array([4], dtype=int64),)
Count of non-zero elements: 7
